// src/utils/mbtiQuestions.js

export const mbtiQuestions = [
  { id: 1, statement_a: 'Spontan, Fleksibel, tidak diikat waktu', statement_b: 'Terencana dan memiliki deadline jelas' },
  { id: 2, statement_a: 'Lebih memilih berkomunikasi dengan menulis', statement_b: 'Lebih memilih berkomunikasi dengan bicara' },
  { id: 3, statement_a: 'Tidak menyukai hal-hal yang bersifat mendadak dan di luar perencanaan', statement_b: 'Perubahan mendadak tidak jadi masalah' },
  { id: 4, statement_a: 'Obyektif', statement_b: 'Subyektif' },
  { id: 5, statement_a: 'Menemukan dan mengembangkan ide dengan mendiskusikannya', statement_b: 'Menemukan dan mengembangkan ide dengan merenungkan' },
  { id: 6, statement_a: 'Bergerak dari gambaran umum baru ke detail', statement_b: 'Bergerak dari detail ke gambaran umum sebagai kesimpulan akhir' },
  { id: 7, statement_a: 'Berorientasi pada dunia eksternal (kegiatan, orang)', statement_b: 'Berorientasi pada dunia internal (memori, pemikiran, ide)' },
  { id: 8, statement_a: 'Berbicara mengenai masalah yang dihadapi hari ini dan langkah-langkah praktis mengatasinya', statement_b: 'Berbicara mengenai visi masa depan dan konsep-konsep mengenai visi tersebut' },
  { id: 9, statement_a: 'Diyakinkan dengan penjelasan yang menyentuh perasaan', statement_b: 'Diyakinkan dengan penjelasan yang masuk akal' },
  { id: 10, statement_a: 'Fokus pada sedikit hobi namun mendalam', statement_b: 'Fokus pada banyak hobi secara luas dan umum' },
  { id: 11, statement_a: 'Tertutup dan mandiri', statement_b: 'Sosial dan ekspresif' },
  { id: 12, statement_a: 'Aturan, jadwal dan target sangat mengikat dan membebani', statement_b: 'Aturan, jadwal dan target akan sangat membantu dan memperjelas tindakan' },
  { id: 13, statement_a: 'Menggunakan pengalaman sebagai pedoman', statement_b: 'Menggunakan imajinasi dan perenungan sebagai pedoman' },
  { id: 14, statement_a: 'Berorientasi tugas dan job description', statement_b: 'Berorientasi pada manusia dan hubungan' },
  { id: 15, statement_a: 'Pertemuan dengan orang lain dan aktivitas sosial melelahkan', statement_b: 'Bertemu orang dan aktivitas sosial membuat bersemangat' },
  { id: 16, statement_a: 'SOP sangat membantu', statement_b: 'SOP sangat membosankan' },
  { id: 17, statement_a: 'Mengambil keputusan berdasar logika dan aturan main', statement_b: 'Mengambil keputusan berdasar perasaan pribadi dan kondisi orang lain' },
  { id: 18, statement_a: 'Bebas dan dinamis', statement_b: 'Prosedural dan tradisional' },
  { id: 19, statement_a: 'Berorientasi pada hasil', statement_b: 'Berorientasi pada proses' },
  { id: 20, statement_a: 'Beraktifitas sendirian di rumah menyenangkan', statement_b: 'Beraktifitas sendirian di rumah membosankan' },
  { id: 21, statement_a: 'Membiarkan orang lain bertindak bebas asalkan tujuan tercapai', statement_b: 'Mengatur orang lain dengan tata tertib agar tujuan tercapai' },
  { id: 22, statement_a: 'Memilih ide inspiratif lebih penting daripada fakta', statement_b: 'Memilih fakta lebih penting daripada ide inspiratif' },
  { id: 23, statement_a: 'Mengemukakan tujuan dan sasaran lebih dahulu', statement_b: 'Mengemukakan kesepakatan terlebih dahulu' },
  { id: 24, statement_a: 'Fokus pada target dan mengabaikan hal-hal baru', statement_b: 'Memperhatikan hal-hal baru dan siap menyesuaikan diri serta mengubah target' },
  { id: 25, statement_a: 'Kontinuitas dan stabilitas lebih diutamakan', statement_b: 'Perubahan dan variasi lebih diutamakan' },
  { id: 26, statement_a: 'Pendirian masih bisa berubah tergantung situasi nantinya', statement_b: 'Berpegang teguh pada pendirian' },
  { id: 27, statement_a: 'Bertindak step by step dengan timeframe yang jelas', statement_b: 'Bertindak dengan semangat tanpa menggunakan timeframe' },
  { id: 28, statement_a: 'Berinisiatif tinggi hampir dalam berbagai hal meskipun tidak berhubungan dengan dirinya', statement_b: 'Berinisiatif bila situasi memaksa atau berhubungan dengan kepentingan sendiri' },
  { id: 29, statement_a: 'Lebih memilih tempat yang tenang dan pribadi untuk berkonsentrasi', statement_b: 'Lebih memilih tempat yang ramai dan banyak interaksi / aktifitas' },
  { id: 30, statement_a: 'Menganalisa', statement_b: 'Berempati' },
  { id: 31, statement_a: 'Berpikir secara matang sebelum bertindak', statement_b: 'Berani bertindak tanpa terlalu lama berfikir' },
  { id: 32, statement_a: 'Menghargai seseorang karena sifat dan perilakunya', statement_b: 'Menghargai seseorang karena skill dan faktor teknis' },
  { id: 33, statement_a: 'Merasa nyaman bila situasi tetap terbuka terhadap pilihan-pilihan lain', statement_b: 'Merasa tenang bila semua sudah diputuskan' },
  { id: 34, statement_a: 'Menarik kesimpulan dengan lama dan hati-hati', statement_b: 'Menarik kesimpulan dengan cepat sesuai naluri' },
  { id: 35, statement_a: 'Mengekspresikan semangat', statement_b: 'Menyimpan semangat dalam hati' },
  { id: 36, statement_a: 'Mengklarifikasi ide dan teori sebelum dipraktekkan', statement_b: 'Memahami ide dan teori saat mempraktekkannya langsung' },
  { id: 37, statement_a: 'Melibatkan perasaan itu tidak profesional', statement_b: 'Terlalu kaku pada peraturan dan pekerjaan itu kejam' },
  { id: 38, statement_a: 'Mencari kesempatan untuk berkomunikasi secara perorangan', statement_b: 'Memilih berkomunikasi pada sekelompok orang' },
  { id: 39, statement_a: 'Yang penting situasi harmonis terjaga', statement_b: 'Yang penting tujuan tercapai' },
  { id: 40, statement_a: 'Ketidakpastian itu seru, menegangkan dan membuat hati lebih senang', statement_b: 'Ketidakpastian membuat bingung dan meresahkan' },
  { id: 41, statement_a: 'Berfokus pada masa kini (apa yang bisa diperbaiki sekarang)', statement_b: 'Berfokus pada masa depan (apa yang mungkin dicapai di masa depan)' },
  { id: 42, statement_a: 'Mempertanyakan', statement_b: 'Mengakomodasi' },
  { id: 43, statement_a: 'Secara konsisten mengamati dan mengingat detail', statement_b: 'Mengamati dan mengingat detail hanya bila berhubungan dengan pola' },
  { id: 44, statement_a: 'Situasi last minute membuat bersemangat dan memunculkan potensi', statement_b: 'Situasi last minute sangat menyiksa, membuat stress dan merupakan kesalahan' },
  { id: 45, statement_a: 'Lebih suka komunikasi tidak langsung (telp, surat, e-mail)', statement_b: 'Lebih suka komunikasi langsung (tatap muka)' },
  { id: 46, statement_a: 'Praktis', statement_b: 'Konseptual' },
  { id: 47, statement_a: 'Perubahan adalah musuh', statement_b: 'Perubahan adalah semangat hidup' },
  { id: 48, statement_a: 'Sering dianggap keras kepala', statement_b: 'Sering dianggap terlalu memihak' },
  { id: 49, statement_a: 'Bersemangat saat menolong orang keluar dari kesalahan dan meluruskan', statement_b: 'Bersemangat saat mengkritik dan menemukan kesalahan' },
  { id: 50, statement_a: 'Bertindak sesuai situasi dan kondisi yang terjadi saat itu', statement_b: 'Bertindak sesuai apa yang sudah direncanakan' },
  { id: 51, statement_a: 'Menggunakan keterampilan yang sudah dikuasai', statement_b: 'Menyukai tantangan untuk menguasai keterampilan baru' },
  { id: 52, statement_a: 'Membangun ide pada saat berbicara', statement_b: 'Membangun ide dengan matang baru membicarakannya' },
  { id: 53, statement_a: 'Memilih cara yang sudah ada dan sudah terbukti', statement_b: 'Memilih cara yang unik dan belum dipraktekkan orang lain' },
  { id: 54, statement_a: 'Hidup harus sudah diatur dari awal', statement_b: 'Hidup seharusnya mengalir sesuai kondisi' },
  { id: 55, statement_a: 'Standar harus ditegakkan di atas segalanya (itu menunjukkan kehormatan dan harga diri)', statement_b: 'Perasaan manusia lebih penting dari sekadar standar (yang adalah benda mati)' },
  { id: 56, statement_a: 'Daftar dan checklist adalah panduan penting', statement_b: 'Daftar dan checklist adalah tugas dan beban' },
  { id: 57, statement_a: 'Menuntut perlakuan yang adil dan sama pada semua orang', statement_b: 'Menuntut perlakuan khusus sesuai karakteristik masing-masing orang' },
  { id: 58, statement_a: 'Mementingkan sebab-akibat', statement_b: 'Mementingkan nilai-nilai personal' },
  { id: 59, statement_a: 'Puas ketika mampu beradaptasi dengan momentum yang terjadi', statement_b: 'Puas ketika mampu menjalankan semuanya sesuai rencana' },
  { id: 60, statement_a: 'Spontan, Easy Going, fleksibel', statement_b: 'Berhati-hati, penuh pertimbangan, kaku' }
];